### ISSUE TITLE
Adding Authors to a Pattern Candidate does not work in while Adding it

### ISSUE THREAD

**Issue by lharzenetter** [PatternAtlas/pattern-atlas-ui#125]
**Describe the bug**
When creating a new Pattern Candidate, adding another author does not work. 

**To Reproduce**
1. Go to Pattern Cadidates
2. Click on Add New
3. Try to add another user as an author

**Expected behavior**
I can add the user as an author.

**Found by**: @mar-be

**Comment by mhinkie** [comment]
UI attempts PUT on http://localhost:1977/patternatlas/issues/undefined/authors since the issue is not yet created. Will change UI for Issues and Candidate to defer setting autors until the save button is clicked

**Comment by mhinkie** [comment]
Fixed in `ba-meyer-master` (see c64b71c)
