### ISSUE TITLE
Add Relation Bug

### ISSUE THREAD

**Issue by mar-be** [PatternAtlas/pattern-atlas-ui#128]
**Describe the bug**
I cannot add a relation via the button in the _Relation to other Patterns_ section of a pattern. It produces the following error in the backend: 
` WARN 13 --- [io-1977-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler io.github.patternatlas.api.rest.exception.RestResponseExceptionHandler#handleStorageExceptions(Exception, WebRequest)
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.hasExplicitTimeZone()`

However, the add-relation button in the overview of the pattern language works although it uses the same API method of the backend.

**To Reproduce**
1. Go to a pattern
2. Scroll down to the section _Relation to other Patterns_ 
3. Click on the button to add a relation
4. Fill out the form and try to save it 

**Expected behavior**
The newly added relation gets stored and appears in the section _Relation to other Patterns_

**Comment by mhinkie** [comment]
Fixed with #165 - see also #157
