### ISSUE TITLE
Add management interface for resource specific roles

### ISSUE THREAD

**Issue by mhinkie** [PatternAtlas/pattern-atlas-ui#143]
**Is your feature request related to a problem? Please describe.**
In the system there are resource specific privileges. For example the privilege for editing the existing issue with ID {id1}, which is saved as ISSUE_EDIT_{id1}. For these privileges defaults are saved in the system as ISSUE_EDIT. These defaults get assigned as soon as a new resource (Issue, Pattern, Pattern candidate...) is created - using the newly created ID.
It is currently not possible to set the resource specifc privileges for the author roles (HELPER, MANTAINER, OWNER).

**Describe the solution you'd like**
In Menu->Admin a third tab should be added (i.e. "Resource specifc privileges"). This tab lists the roles (HELPER, MANTAINER, OWNER) as columns and the resource specific privileges (ISSUE_READ, ISSUE_EDIT, PATTERN_CANDIDATE_EDIT,... - all roles not ending with _ALL or ISSUE_CREATE) in rows. The tab can look similar to "Role & Privilege Management".

This tab shows the default privileges that get assigned to issues and pattern candidates. These defaults are saved as the privileges mentioined above and this tab then allows to change these defaults for the different author roles. If one of the defaults is changed a popup should ask the user if - in addition the defaults - also the already existing resource specific privileges should be changed. 

Example: ISSUE_EDIT is changed and the user wants to change all already assigned privileges aswell (accepts popup). Since ISSUE_EDIT_{id} is found in the system for 4 different ids, also the privileges ISSUE_EDIT_id1, ISSUE_EDIT_id2, ISSUE_EDIT_id3, ISSUE_EDIT_id4 will be changed.

**Additional context**
For a full list of privileges in the system see 
src/main/java/io/github/patternatlas/auth/defaultSetup/SetupDataLoader.java
in the api. Note that this change only concerns privileges not containing "_ALL" in their name aswell as not the privilege "ISSUE_CREATE".

**Comment by PhilWun** [comment]
Implemented in 967dc47817751eef6fd45c8929cf506be91f44f8 and previous commits.
Endpoints implemented in https://github.com/PatternAtlas/pattern-atlas-api/commit/075e9b38161fc2cb6887ab8cf7d23cd81079ba09 and previous commits.
