### ISSUE TITLE
Fix import / usage of Katex dependency

### ISSUE THREAD

**Issue by marzn** [PatternAtlas/pattern-atlas-ui#38]
Katex is loaded from CDN in index.html in [L26](https://github.com/PatternPedia/pattern-pedia-views-ui/blob/c5a926d4d2d23acfc347e9d14ae2c2362283245a/src/index.html#L26) and [L32-40](https://github.com/PatternPedia/pattern-pedia-views-ui/blob/c5a926d4d2d23acfc347e9d14ae2c2362283245a/src/index.html#L32) and it is defined as dev dependency in [package.json](https://github.com/PatternPedia/pattern-pedia-views-ui/blob/c5a926d4d2d23acfc347e9d14ae2c2362283245a/package.json#L67) which does not seem to be correct.

**Todo**
* [ ] Decide whether to use a CDN or define it as dependency (not dev)
* [ ] Clean up code in index.html and/or package.json

**Comment by mbeisel** [comment]
got fixed in branch masterthesis/patternauthoring and will be merged with the next content integration

**Comment by manuwei** [comment]
this issue was resolved and is no longer present on the master branch
