### ISSUE TITLE
Inconsistent URLs style, use kebab-case everywhere

### ISSUE THREAD

**Issue by marzn** [PatternAtlas/pattern-atlas-ui#47]
URLs are inconsistently written in camelCase and kebab-case.

For example L31 and L72: https://github.com/PatternPedia/pattern-pedia-views-ui/blob/f0a77e0717d66fd2ff060dd2f9e41e7782264578/src/app/app-routing.module.ts

All URL paths should be kebab-case, avoid camelCase.

**Comment by manuwei** [comment]
this issue was resolved for all modules (except the DesignModelRoutingModule) and is therefore no longer present on the master branch
