### ISSUE TITLE
Pattern details are broken

### ISSUE THREAD

**Issue by marzn** [PatternAtlas/pattern-atlas-ui#52]
**Describe the bug**
The pattern details are broken

**To Reproduce**
1. Go to a pattern language
2. Click on the 'Details' button of a pattern
3. Pattern details will not load, even the spinner indicates loading. An error is logged on the console `Cannot read property 'href' of undefined`

**Expected behavior**
Pattern details should be loaded ;)

**Screenshot**
![Screenshot from 2020-06-09 17-54-45](https://user-images.githubusercontent.com/13757952/84171295-f288b900-aa7a-11ea-9984-3b13f7811bd1.png)

**Comment by pascalhuszar** [comment]
Can't reporduce this issue/bug. Which branch do you work on? 
I checked _master_ and current branch im working on _change-to-uri-links_

Besides i can't found Message Router in my db

**Comment by manuwei** [comment]
this issue was resolved and is no longer present on the master branch
