### ISSUE TITLE
Setup a ReadTheDocs documentation

### ISSUE THREAD

**Issue by manuwei** [PatternAtlas/pattern-atlas-ui#77]
A detailled ReadTheDocs documentation (an example can be found here: [Quantil ReadTheDocs](/quantil.readthedocs.io/en/latest/) - [Source Code](https://github.com/UST-QuAntiL/quantil-docs) ) would be helpful to have an overview documentation page for all patternatlas repos

**Comment by mbeisel** [comment]
moved away to seperate repository: https://github.com/PatternAtlas/pattern-atlas-readthedocs

**Comment by manuwei** [comment]
can be found at: https://pattern-atlas-readthedocs.readthedocs.io/en/latest/
